#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/smartisan/trident

PRODUCT_COPY_FILES += \
    vendor/smartisan/trident/proprietary/recovery/root/system/etc/logic_volume.conf:$(TARGET_COPY_OUT_RECOVERY)/root/system/etc/logic_volume.conf \
    vendor/smartisan/trident/proprietary/system/etc/permissions/audiosphere.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/audiosphere.xml \
    vendor/smartisan/trident/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/smartisan/trident/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/smartisan/trident/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/smartisan/trident/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/smartisan/trident/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/smartisan/trident/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/smartisan/trident/proprietary/system_ext/etc/permissions/telephonyservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephonyservice.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/MTP/MTP_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Codec_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_workspaceFile.qwsp \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/QRD/QRD_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Codec_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/smartisan/trident/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/smartisan/trident/proprietary/vendor/etc/cacert_location.pem:$(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO270_2944X2944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO270_2944X2944.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO270_4032X2016.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO270_4032X2016.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO270_4032X2268.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO270_4032X2268.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO270_4032X3024.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO270_4032X3024.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO400_2944X2944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO400_2944X2944.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO400_4032X2016.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO400_4032X2016.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO400_4032X2268.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO400_4032X2268.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO400_4032X3024.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO400_4032X3024.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO560_2944X2944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO560_2944X2944.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO560_4032X2016.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO560_4032X2016.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO560_4032X2268.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO560_4032X2268.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO560_4032X3024.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO560_4032X3024.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO720_2944X2944.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO720_2944X2944.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO720_4032X2016.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO720_4032X2016.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO720_4032X2268.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO720_4032X2268.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/camera/sensor_denoise_table/imx363/ISO720_4032X3024.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sensor_denoise_table/imx363/ISO720_4032X3024.ncf \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/profileSlm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileSlm.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/slm.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/slm.conf \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/configstore/vpp.configstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/configstore/vpp.configstore.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/effects/imagis_phe.bin:$(TARGET_COPY_OUT_VENDOR)/etc/effects/imagis_phe.bin \
    vendor/smartisan/trident/proprietary/vendor/etc/elliptic_sensor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/elliptic_sensor.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/init/android.hardware.biometrics.fpcfingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fpcfingerprint@2.1-service.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/android.hardware.biometrics.goodixfingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.goodixfingerprint@2.1-service.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/android.hardware.biometrics.nvtfingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.nvtfingerprint@2.1-service.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/android.hardware.gnss@2.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.1-service-qti.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/ims_rtp_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/init-qcril-data.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init-qcril-data.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/ipa_fws.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipa_fws.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/logic_volume.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/logic_volume.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/vendor.qti.esepowermanager@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.esepowermanager@1.0-service.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/init/vppservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vppservice.rc \
    vendor/smartisan/trident/proprietary/vendor/etc/logic_volume.conf:$(TARGET_COPY_OUT_VENDOR)/etc/logic_volume.conf \
    vendor/smartisan/trident/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/smartisan/trident/proprietary/vendor/etc/qdcm_calib_data_td4362_1080p_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_td4362_1080p_cmd_mode_dsi_panel.xml \
    vendor/smartisan/trident/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/smartisan/trident/proprietary/vendor/etc/scve/facereco/gModel.dat:$(TARGET_COPY_OUT_VENDOR)/etc/scve/facereco/gModel.dat \
    vendor/smartisan/trident/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/8909w_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/8909w_ak991x_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/8909w_bmi160_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/8909w_bmi160_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/8909w_bmp285_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/8909w_bmp285_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/8909w_ltr308_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/8909w_ltr308_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/8909w_pah_8011_0_platform.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/8909w_pah_8011_0_platform.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/8909w_pah_8011_0_ppg.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/8909w_pah_8011_0_ppg.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/8909w_pah_8011_0_touch.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/8909w_pah_8011_0_touch.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/bme680_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bme680_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/bmi160_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bmi160_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/bmp285_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bmp285_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/bu52272nuz_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bu52272nuz_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/cm3526_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/cm3526_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/config_list.txt:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/config_list.txt \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/icm206xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/icm206xx_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/ltr308_0_on_change.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ltr308_0_on_change.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/mmc5603nj_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mmc5603nj_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/msm8996_ak9911x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msm8996_ak9911x_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/msm8996_bmp285_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msm8996_bmp285_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/msm8996_cm3526_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msm8996_cm3526_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/msm8996_lsm6ds3_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msm8996_lsm6ds3_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/msm8996_lsm6dsm_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msm8996_lsm6dsm_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/msm8996_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msm8996_power_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/msm8996_shtw2_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msm8996_shtw2_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/msm8996_tmx4903.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/msm8996_tmx4903.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/qcs605_bmi160_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qcs605_bmi160_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm670_2p5K_tmx4903.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_2p5K_tmx4903.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm670_4K_tmx4903.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_4K_tmx4903.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm670_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_ak991x_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm670_bmp285_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_bmp285_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm670_cm3526_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_cm3526_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm670_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_lsm6dso_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm670_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_power_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm670_qrd_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_qrd_ak991x_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm670_qrd_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_qrd_lsm6dso_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm670_shtw2_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_shtw2_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm670_tmx4903.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm670_tmx4903.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_2p5K_tmx4903.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_2p5K_tmx4903.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_4K_tmx4903.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_4K_tmx4903.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_ak991x_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_bme680_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_bme680_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_bmi160_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_bmi160_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_bmp285_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_bmp285_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_bu52272nuz_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_bu52272nuz_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_cm3526_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_cm3526_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_icm206xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_icm206xx_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_mmc5603nj_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_mmc5603nj_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_power_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_shtw2_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_shtw2_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_tmx4903.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_tmx4903.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sdm845_tsl258x.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_tsl258x.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/shtw2_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/shtw2_0.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/smartisan_housing_color.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/smartisan_housing_color.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_oem1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_oem1.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/tmx4903.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tmx4903.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/config/tsl258x.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tsl258x.json \
    vendor/smartisan/trident/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/smartisan/trident/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/smartisan/trident/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/smartisan/trident/proprietary/vendor/etc/thermal-engine-845.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-845.conf \
    vendor/smartisan/trident/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/smartisan/trident/proprietary/vendor/etc/vstab_db_0_1080p_video_30fps.config:$(TARGET_COPY_OUT_VENDOR)/etc/vstab_db_0_1080p_video_30fps.config \
    vendor/smartisan/trident/proprietary/vendor/etc/vstab_db_0_1080p_video_60fps.config:$(TARGET_COPY_OUT_VENDOR)/etc/vstab_db_0_1080p_video_60fps.config \
    vendor/smartisan/trident/proprietary/vendor/etc/vstab_db_0_4k_video_30fps.config:$(TARGET_COPY_OUT_VENDOR)/etc/vstab_db_0_4k_video_30fps.config \
    vendor/smartisan/trident/proprietary/vendor/etc/vstab_db_0_720p_video_30fps.config:$(TARGET_COPY_OUT_VENDOR)/etc/vstab_db_0_720p_video_30fps.config \
    vendor/smartisan/trident/proprietary/vendor/etc/vstab_db_1_1080p_video_30fps.config:$(TARGET_COPY_OUT_VENDOR)/etc/vstab_db_1_1080p_video_30fps.config \
    vendor/smartisan/trident/proprietary/vendor/etc/vstab_db_1_720p_video_30fps.config:$(TARGET_COPY_OUT_VENDOR)/etc/vstab_db_1_720p_video_30fps.config \
    vendor/smartisan/trident/proprietary/vendor/etc/xtra_root_cert.pem:$(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    vendor/smartisan/trident/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/smartisan/trident/proprietary/vendor/firmware/a630_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_gmu.bin \
    vendor/smartisan/trident/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/smartisan/trident/proprietary/vendor/firmware/a630_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.b00 \
    vendor/smartisan/trident/proprietary/vendor/firmware/a630_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.b01 \
    vendor/smartisan/trident/proprietary/vendor/firmware/a630_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.b02 \
    vendor/smartisan/trident/proprietary/vendor/firmware/a630_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.elf \
    vendor/smartisan/trident/proprietary/vendor/firmware/a630_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.mdt \
    vendor/smartisan/trident/proprietary/vendor/firmware/debussy.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/debussy.bin \
    vendor/smartisan/trident/proprietary/vendor/firmware/firmware.img:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware.img \
    vendor/smartisan/trident/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/smartisan/trident/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/smartisan/trident/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/smartisan/trident/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/smartisan/trident/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/smartisan/trident/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/smartisan/trident/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/smartisan/trident/proprietary/vendor/firmware/libpn553_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn553_fw.so \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.sensormodule.ofilm_imx350.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.ofilm_imx350.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.sensormodule.ofilm_imx363.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.ofilm_imx363.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.sensormodule.ofilm_s5k2x7sp.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.ofilm_s5k2x7sp.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.sensormodule.sunny_imx350.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.sunny_imx350.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.sensormodule.sunny_imx363.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.sunny_imx363.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.sensormodule.sunny_s5k2x7sp.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.sunny_s5k2x7sp.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.default.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.tuned.ofilm_imx350.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.ofilm_imx350.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.tuned.ofilm_imx363.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.ofilm_imx363.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.tuned.ofilm_s5k2x7sp.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.ofilm_s5k2x7sp.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.tuned.sunny_imx350.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.sunny_imx350.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.tuned.sunny_imx363.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.sunny_imx363.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/com.qti.tuned.sunny_s5k2x7sp.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.sunny_s5k2x7sp.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreview.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreviewlite.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideo.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideolite.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/imx258tuned.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/imx258tuned.bin \
    vendor/smartisan/trident/proprietary/vendor/lib/camera/systemdefault.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/systemdefault.bin \
    vendor/smartisan/trident/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/smartisan/trident/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/smartisan/trident/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/smartisan/trident/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/smartisan/trident/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/smartisan/trident/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/smartisan/trident/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    vendor/smartisan/trident/proprietary/vendor/radio/qcril_database/upgrade/6_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    vendor/smartisan/trident/proprietary/vendor/radio/qcril_database/upgrade/7_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vulkan.adreno \
    libC2D2 \
    libCB \
    libOpenCL \
    libQSEEComAPI \
    libVkLayer_q3dtools \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libc2d30_bltlib \
    libcdsp_default_listener \
    libcdsprpc \
    libdiag \
    libdsutils \
    libfastcvdsp_stub \
    libfastcvopt \
    libgpudataproducer \
    libgsl \
    libidl \
    libllvm-glnext \
    libllvm-qcom \
    libmdmdetect \
    libpvr \
    libqcbor \
    libqcmaputils \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libscveBlobDescriptor \
    libscveBlobDescriptor_stub \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libscvePanorama \
    libscvePanorama_lite \
    libscveScan3D \
    libsdsprpc \
    libsensorslog \
    libssc \
    libsysmon_cdsp_skel \
    libthermalclient \
    libtime_genoff \
    libvppclient \
    libvpphvx \
    libvpplibrary \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    btaudio_offload_if \
    com.qti.sensor.imx318 \
    com.qti.sensor.imx350 \
    com.qti.sensor.imx362 \
    com.qti.sensor.imx363 \
    com.qti.sensor.ov12a10 \
    com.qti.sensor.ov13855 \
    com.qti.sensor.ov13880 \
    com.qti.sensor.ov8856 \
    com.qti.sensor.s5k2x7sp \
    com.arcsoft.node.capturebokeh \
    com.arcsoft.node.realtimebokeh \
    com.inv.node.eis \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.arc_mfnr \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.panorama \
    com.qti.node.remosaic \
    com.qti.node.smzslpreview \
    com.qti.node.smzslsnapshot \
    com.qti.node.snapshot_superzoom \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.node.tt_hdr \
    com.qti.node.videozoom \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    audio.primary.sdm845 \
    camera.qcom \
    com.qti.chi.override \
    sound_trigger.primary.sdm845 \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    libHalSuperSensorServer \
    libOmxVpp \
    libSNPE \
    libSensorManagerHAL \
    libSuperSensor \
    libSuperSensorCPU \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadpcmdec \
    libarcintegration \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_shot \
    libarcsoft_mpbase_sm \
    libarcsoft_picselfie_algorithm \
    libarcsoft_smart_denoise \
    libaudcal \
    libaudio_log_utils \
    libaudioalsa \
    libaudioparsers \
    libbeauty_momo_sm \
    libbluetooth_audio_session_qti \
    libcamxfdalgov7 \
    libcamxfdengine \
    libcamxstatscore \
    libcamxtintlessalgo \
    libcapiv2svacnn \
    libcapiv2vop \
    libcom.qti.chinodeutils \
    libfastcrc \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libgnustl_shared \
    libimgcmp_jni \
    liblistenjni \
    liblistensoundmodel2 \
    libmmcamera_dbg \
    libmmcamera_hdr_tt_lib \
    libmmcv_sm \
    libmms_gyro_vstab \
    libmms_gyro_vstab_auth \
    libmms_hal_vstab \
    libmms_warper_vstab \
    libmpbase \
    libmulawdec \
    libnative-lib \
    libqtigef \
    libsmart_autohdr \
    libsmcinvokecred \
    libsmcv \
    libsmwrapper \
    libsnpe_loader \
    libsymphony-cpu \
    libsymphonypower \
    libtiff \
    libtt_panorama \
    libvideoprocess \
    libyuvutils_sm \
    libasphere \
    libshoebox \
    com.fingerprints.extension@1.0 \
    com.novatek.fingerprint@1.0_vendor \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    com.qualcomm.qti.imscmservice@1.0_vendor \
    com.qualcomm.qti.imscmservice@2.0_vendor \
    com.qualcomm.qti.imscmservice@2.1_vendor \
    com.qualcomm.qti.imscmservice@2.2_vendor \
    com.qualcomm.qti.uceservice@2.0_vendor \
    com.qualcomm.qti.uceservice@2.1_vendor \
    com.qualcomm.qti.uceservice@2.2_vendor \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.gnss@2.1-impl-qti \
    android.hardware.keymaster@3.0-impl-qti \
    nvtfingerprint.default \
    vendor.qti.esepowermanager@1.0-impl \
    vendor.qti.gnss@4.0-impl \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.bluetooth_sar@1.0-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.fm@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    vendor.qti.hardware.soter@1.0-impl \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsvtcore \
    lib-imsxml \
    lib-rcsconfig \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libGPQTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libQTEEConnector_vendor \
    libSecureUILib \
    libStDrvInt \
    libaoa \
    libbatching \
    libbtnv \
    libcacertclient \
    libcdfw_remote_api \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcneqmiutils \
    libconfigdb \
    libcpion \
    libdataitems \
    libdisp-aba \
    libdisplayqos \
    libdpmqmihal \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libfpr_ca \
    libfpr_library \
    libgdtap \
    libgeofencing \
    libgf_ca \
    libgf_hal \
    libgnss \
    libgnsspps \
    libgoodixfingerprintd_binder \
    libgoodixhwfingerprint \
    libgps.utils \
    libhdr_tm \
    libhexagon_nn_stub \
    libizat_client_api \
    libizat_core \
    libjnihelper \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    liblbs_core \
    libloc_api_v02 \
    libloc_core \
    libloc_socket \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libminkdescriptor \
    libminksocket \
    libmmosal_vendor \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnlnetmgr \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libqcc_file_agent \
    libqcrilFramework \
    libqcrildatactl \
    libqdi \
    libqdma_file_agent \
    libqdp \
    libqisl \
    libqrtr \
    libqseed3 \
    libqsocket \
    librcc \
    libril-qc-hal-qmi \
    libril-qc-logger \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librpmb \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsecureui \
    libsecureui_svcsock \
    libsensorcal \
    libsettings \
    libslimclient \
    libsmartisan_cjson \
    libsns_low_lat_stream_stub \
    libsnsdiaglog \
    libspcom \
    libspl \
    libssc_default_listener \
    libssd \
    libsystem_health_mon \
    libtinyxml2_1 \
    libtrustedapploader \
    libtzdrmgenprov \
    libwms \
    libwqe \
    libwvhidl \
    libxml \
    libxtadapter \
    libwvdrmengine \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    sensors.elliptic \
    sensors.ssc \
    unnhal-acc-adreno \
    unnhal-acc-common \
    unnhal-acc-hvx \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.goodix.hardware.fingerprintextension@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.gnss@4.0-service \
    vendor.qti.gnss@4.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0_vendor \
    vendor.qti.hardware.data.cne.internal.constants@1.0_vendor \
    vendor.qti.hardware.data.cne.internal.server@1.0_vendor \
    vendor.qti.hardware.data.connection@1.0_vendor \
    vendor.qti.hardware.data.connection@1.1_vendor \
    vendor.qti.hardware.data.dynamicdds@1.0_vendor \
    vendor.qti.hardware.data.iwlan@1.0_vendor \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.qmi@1.0_vendor \
    vendor.qti.hardware.fm@1.0_vendor \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.qti.hardware.radio.ims@1.0_vendor \
    vendor.qti.hardware.radio.ims@1.1_vendor \
    vendor.qti.hardware.radio.ims@1.2_vendor \
    vendor.qti.hardware.radio.ims@1.3_vendor \
    vendor.qti.hardware.radio.ims@1.4_vendor \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.hardware.soter@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0_vendor \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.rcsconfig@1.0_vendor \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.imsrtpservice@3.0_vendor \
    vendor.qti.latency@2.0 \
    capi_v2_aptX_Classic \
    capi_v2_aptX_HD \
    dirac_resource \
    libBeautyShot_skel \
    libFastRPC_UTF_Forward_skel \
    libSuperSensor_skel \
    libVC1Dec \
    libVC1DecDsp_skel \
    libapps_mem_heap \
    libarcsoft_dualcam_refocus_skel \
    libdirac-capiv2 \
    libdspCV_skel \
    libdsp_streamer_add_constant \
    libdsp_streamer_skel \
    libexternal_dog_skel \
    libfastcvadsp \
    libfastcvdsp_skel \
    libhexagon_nn_skel \
    libhvxMathVIO \
    libscveBlobDescriptor_skel \
    libscveT2T_skel \
    libsns_low_lat_stream_skel \
    libdiag_system \
    vendor.qti.diaghal@1.0 \
    com.qualcomm.qti.dpm.api@1.0 \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.api@1.1 \
    com.quicinc.cne.constants@1.0 \
    com.quicinc.cne.constants@2.0 \
    com.quicinc.cne.constants@2.1 \
    fm_helium \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libfm-hci \
    libimscamera_jni \
    libimsmedia_jni \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.imsrtpservice@3.0 \
    CneApp \
    IWlanService \
    TimeService \
    PowerOffAlarm \
    QtiTelephonyService \
    uceShimService \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel \
    audiosphere \
    tcmclient \
    com.qti.dpmframework \
    com.quicinc.cne.api-V1.1-java \
    com.quicinc.cne.constants-V1.0-java \
    com.quicinc.cne.constants-V2.0-java \
    com.quicinc.cne.constants-V2.1-java \
    dpmapi \
    qcrilhook \
    vendor.qti.hardware.data.cne.internal.api-V1.0-java \
    vendor.qti.hardware.data.cne.internal.constants-V1.0-java \
    vendor.qti.hardware.data.connection-V1.0-java \
    vendor.qti.hardware.data.connection-V1.1-java \
    vendor.qti.hardware.data.dynamicdds-V1.0-java \
    vendor.qti.hardware.data.iwlan-V1.0-java \
    vendor.qti.hardware.data.qmi-V1.0-java \
    android.hardware.gnss@2.1-service-qti.xml \
    android.hardware.neuralnetworks@1.3-service-qti.xml \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    vendor.qti.gnss@4.0-service.xml \
    ATFWD-daemon \
    adpl \
    adsprpcd \
    cdsprpcd \
    cnd \
    cnss-daemon \
    dm-tool \
    dm-tool.recovery \
    dpmQmiMgr \
    hvdcp_opti \
    android.hardware.biometrics.fpcfingerprint@2.1-service \
    android.hardware.biometrics.goodixfingerprint@2.1-service \
    android.hardware.biometrics.nvtfingerprint@2.1-service \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.gnss@2.1-service-qti \
    android.hardware.keymaster@3.0-service-qti \
    android.hardware.neuralnetworks@1.3-service-qti \
    qcrild \
    vendor.display.color@1.0-service \
    vendor.qti.esepowermanager@1.0-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    vendor.qti.hardware.soter@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    ks \
    loc_launcher \
    logic_volume \
    logic_volume.recovery \
    lowi-server \
    mlid \
    mm-pp-dpps \
    msm_irqbalance \
    netmgrd \
    pd-mapper \
    pm-proxy \
    pm-service \
    port-bridge \
    power_off_alarm \
    ppd \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    rmt_storage \
    seemp_healthd \
    sensors.qti \
    slim_daemon \
    ssgqmigd \
    ssgtzd \
    tftp_server \
    thermal-engine \
    time_daemon \
    vppservice \
    xtra-daemon \
    xtwifi-client \
    xtwifi-inet-agent \
    dpmd

PRODUCT_PACKAGES += \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib_libq3dtools_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so
